### ISSUE TITLE
对接 Gitbook

### ISSUE THREAD

**Issue by xyy94813** [1046102779/prometheus#12]
可以考虑对接 Gitbook 阅读更方便

**Comment by 1046102779** [comment]
好的，最近我对接下

**Comment by 1046102779** [comment]
GITBOOK搞了下，蛮多问题，
用了一个替代阅读：
https://love2.io/@1046102779/doc/prometheus/introductions/overview.md

**Comment by xyy94813** [comment]
... Gitbook 不是可以直接自动同步 Github 的项目么.
不过 Gitbook 时不时突然让你翻墙... 也是挺麻烦的... 
对了，地址你可以直接配项目这里～
![image](https://user-images.githubusercontent.com/17971352/43811546-99ccc730-9aef-11e8-90e7-ac0de8f80183.png)
